config/routes.rb
Gos::Application.routes.draw do
  
  resources :os
  
  root to: "os#index"
  	

end

app/models/o.rb
class O < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/os_controller.rb
class OsController < ApplicationController
  before_action :set_o, only: [:show, :edit, :update, :destroy]

  http_basic_authenticate_with name: "admin", password: "412pdx6160", except: [:index, :show]
  
  # GET /os
  # GET /os.json
  def index
    @os = O.all
  end

  # GET /os/1
  # GET /os/1.json
  def show
  end

  # GET /os/new
  def new
    @o = O.new
  end

  # GET /os/1/edit
  def edit
  end

  # POST /os
  # POST /os.json
  def create
    @o = O.new(o_params)

    respond_to do |format|
      if @o.save
        format.html { redirect_to @o, notice: 'OS criada com sucesso.' }
        format.json { render action: 'show', status: :created, location: @o }
      else
        format.html { render action: 'new' }
        format.json { render json: @o.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /os/1
  # PATCH/PUT /os/1.json
  def update
    respond_to do |format|
      if @o.update(o_params)
        format.html { redirect_to @o, notice: 'OS atualizada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @o.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /os/1
  # DELETE /os/1.json
  def destroy
    @o.destroy
    respond_to do |format|
      format.html { redirect_to os_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_o
      @o = O.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def o_params
      params.require(:o).permit(:numero, :cliente, :itens, :status, :obs)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/os_helper.rb
module OsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GOS</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="div">

<%= yield %>

</div>
</body>
</html>

app/views/os/_form.html.erb
<%= form_for(@o) do |f| %>
  <% if @o.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@o.errors.count, "error") %> prohibited this OS from being saved:</h2>

      <ul>
      <% @o.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numero %><br>
    <%= f.text_field :numero %>
  </div>
  <div class="field">
    <%= f.label :cliente %><br>
    <%= f.text_field :cliente %>
  </div>
  <div class="field">
    <%= f.label :itens %><br>
    <%= f.text_field :itens %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :obs %><br>
    <%= f.text_field :obs %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/os/edit.html.erb
<h1>Editando OS</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @o %> |
<%= link_to 'Voltar', os_path %>

app/views/os/index.html.erb
<h1>Listando Ordens de Serviço</h1>

<table>
  <thead>
    <tr>
      <th>Nº</th>
      <th>Cliente</th>
      <th>Status</th>
      <th>Obs</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @os.each do |o| %>
	 <% if o.status != "Finalizada" %>
	 <% if o.status != "Encerrada" %>
      <tr>
        <td><%= link_to o.numero, o %></td>
        <td><%= link_to o.cliente, o %></td>
        <td><%= o.status %></td>
        <td><%= o.obs %></td>
        <td><%= link_to 'Editar ', edit_o_path(o) %></td>
        <td><%= link_to 'Excluir', o, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
	 <% end %>  
	 <% end %>  
    <% end %>
  </tbody>
</table>

</br>
</br>

<table>
  <thead>
    <tr>
      <th>Nº</th>
      <th>Cliente</th>
      <th>Status</th>
      <th>Obs</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @os.each do |o| %>
	 <% if o.status == "Finalizada" %>
      <tr>
        <td><%= link_to o.numero, o %></td>
        <td><%= link_to o.cliente, o %></td>
        <td><%= o.status %></td>
        <td><%= o.obs %></td>
        <td><%= link_to 'Editar ', edit_o_path(o) %></td>
        <td><%= link_to 'Excluir', o, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
	 <% end %>  
    <% end %>
  </tbody>
</table>

</br>

<table>
  <thead>
    <tr>
      <th>Nº</th>
      <th>Cliente</th>
      <th>Status</th>
      <th>Obs</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @os.each do |o| %>
	 <% if o.status == "Encerrada" %>
      <tr>
        <td><%= link_to o.numero, o %></td>
        <td><%= link_to o.cliente, o %></td>
        <td><%= o.status %></td>
        <td><%= o.obs %></td>
        <td><%= link_to 'Editar ', edit_o_path(o) %></td>
        <td><%= link_to 'Excluir', o, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
	 <% end %>  
    <% end %>
  </tbody>
</table>

  
</br>

<%= link_to 'Nova OS', new_o_path %>

app/views/os/new.html.erb
<h1>Nova OS</h1>

<%= render 'form' %>

<%= link_to 'Voltar', os_path %>

app/views/os/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>OS <%= @o.numero %></strong>
  <br> <%= @o.cliente %> </br>
</p>

<p>
  <strong>Itens</strong>
  <br> <%= @o.itens %> </br>
</p>

<p>
  <strong>Status</strong>
  <br> <%= @o.status %> </br>
</p>

<p>
  <strong>Obs</strong>
  <%= @o.obs %>
</p>
<br/>

<%= link_to 'Editar', edit_o_path(@o) %> |
<%= link_to 'Voltar', os_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>